
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed dolar1;
	private global::Gtk.Label peso2;
	private global::Gtk.Entry peso;
	private global::Gtk.Label cambiar;
	private global::Gtk.Entry cambio;
	private global::Gtk.Entry dolar;
	private global::Gtk.Button limpia;
	private global::Gtk.Button cambia;
	private global::Gtk.Label dolares;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.dolar1 = new global::Gtk.Fixed ();
		this.dolar1.Name = "dolar1";
		this.dolar1.HasWindow = false;
		// Container child dolar1.Gtk.Fixed+FixedChild
		this.peso2 = new global::Gtk.Label ();
		this.peso2.Name = "peso2";
		this.peso2.LabelProp = global::Mono.Unix.Catalog.GetString ("Pesos");
		this.dolar1.Add (this.peso2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.dolar1 [this.peso2]));
		w1.X = 55;
		w1.Y = 49;
		// Container child dolar1.Gtk.Fixed+FixedChild
		this.peso = new global::Gtk.Entry ();
		this.peso.CanFocus = true;
		this.peso.Name = "peso";
		this.peso.IsEditable = true;
		this.peso.InvisibleChar = '●';
		this.dolar1.Add (this.peso);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.dolar1 [this.peso]));
		w2.X = 43;
		w2.Y = 81;
		// Container child dolar1.Gtk.Fixed+FixedChild
		this.cambiar = new global::Gtk.Label ();
		this.cambiar.Name = "cambiar";
		this.cambiar.LabelProp = global::Mono.Unix.Catalog.GetString ("Tipo de cambio");
		this.dolar1.Add (this.cambiar);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.dolar1 [this.cambiar]));
		w3.X = 55;
		w3.Y = 131;
		// Container child dolar1.Gtk.Fixed+FixedChild
		this.cambio = new global::Gtk.Entry ();
		this.cambio.CanFocus = true;
		this.cambio.Name = "cambio";
		this.cambio.IsEditable = true;
		this.cambio.InvisibleChar = '●';
		this.dolar1.Add (this.cambio);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.dolar1 [this.cambio]));
		w4.X = 42;
		w4.Y = 172;
		// Container child dolar1.Gtk.Fixed+FixedChild
		this.dolar = new global::Gtk.Entry ();
		this.dolar.CanFocus = true;
		this.dolar.Name = "dolar";
		this.dolar.IsEditable = true;
		this.dolar.InvisibleChar = '●';
		this.dolar1.Add (this.dolar);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.dolar1 [this.dolar]));
		w5.X = 252;
		w5.Y = 130;
		// Container child dolar1.Gtk.Fixed+FixedChild
		this.limpia = new global::Gtk.Button ();
		this.limpia.CanFocus = true;
		this.limpia.Name = "limpia";
		this.limpia.UseUnderline = true;
		this.limpia.BorderWidth = ((uint)(6));
		this.limpia.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.dolar1.Add (this.limpia);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.dolar1 [this.limpia]));
		w6.X = 165;
		w6.Y = 233;
		// Container child dolar1.Gtk.Fixed+FixedChild
		this.cambia = new global::Gtk.Button ();
		this.cambia.CanFocus = true;
		this.cambia.Name = "cambia";
		this.cambia.UseUnderline = true;
		this.cambia.BorderWidth = ((uint)(6));
		this.cambia.Label = global::Mono.Unix.Catalog.GetString ("Cambiar");
		this.dolar1.Add (this.cambia);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.dolar1 [this.cambia]));
		w7.X = 275;
		w7.Y = 231;
		// Container child dolar1.Gtk.Fixed+FixedChild
		this.dolares = new global::Gtk.Label ();
		this.dolares.Name = "dolares";
		this.dolares.LabelProp = global::Mono.Unix.Catalog.GetString ("Pesos en Dolares");
		this.dolar1.Add (this.dolares);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.dolar1 [this.dolares]));
		w8.X = 279;
		w8.Y = 97;
		this.Add (this.dolar1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 438;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.limpia.Clicked += new global::System.EventHandler (this.OnLimpiaClicked);
		this.cambia.Clicked += new global::System.EventHandler (this.OnCambiaClicked);
	}
}
